"""work_location and learning_context

Revision ID: 3f301da84c24
Revises: 9e2314ad8e8f
Create Date: 2026-03-12 22:47:24.519282

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f301da84c24'
down_revision = '9e2314ad8e8f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('learning_context',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('task_count', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('daily_checkins', schema=None) as batch_op:
        batch_op.add_column(sa.Column('work_location', sa.String(length=10), nullable=True))

    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('work_location', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_column('work_location')

    with op.batch_alter_table('daily_checkins', schema=None) as batch_op:
        batch_op.drop_column('work_location')

    op.drop_table('learning_context')
    # ### end Alembic commands ###
